insert into Todo(id, username,description,target_Date,is_Done) values(10001,'basharusr','learn JPA',sysdate(),false);
insert into Todo(id, username,description,target_Date,is_Done) values(10002,'basharusr','learn React',sysdate(),false);
insert into Todo(id, username,description,target_Date,is_Done) values(10003,'basharusr','learn Spring Boot',sysdate(),false);
insert into Todo(id, username,description,target_Date,is_Done) values(10004,'basharusr','learn Microservices',sysdate(),false);
insert into Todo(id, username,description,target_Date,is_Done) values(10005,'basharusr','learn HTML',sysdate(),false);
insert into Todo(id, username,description,target_Date,is_Done) values(10006,'basharusr','learn Javascript',sysdate(),false);
insert into Todo(id, username,description,target_Date,is_Done) values(10007,'KOKO77','learn CSS3',sysdate(),false);
insert into Todo(id, username,description,target_Date,is_Done) values(10008,'KOKO77','learn JPA',sysdate(),false);
insert into Todo(id, username,description,target_Date,is_Done) values(10009,'KOKO77','learn React',sysdate(),false);
insert into Todo(id, username,description,target_Date,is_Done) values(10010,'KOKO77','learn Spring Boot',sysdate(),false);
insert into Todo(id, username,description,target_Date,is_Done) values(10011,'KOKO77','learn Microservices',sysdate(),false);
insert into Todo(id, username,description,target_Date,is_Done) values(10012,'KOKO77','learn HTML',sysdate(),false);
insert into Todo(id, username,description,target_Date,is_Done) values(10013,'Yaman','learn Javascript',sysdate(),false);
insert into Todo(id, username,description,target_Date,is_Done) values(10014,'Ahmad','learn CSS3',sysdate(),false);
